### ISSUE TITLE
Academic Citing

### ISSUE THREAD

**Issue by roskoN** [nreimers/truecaser#1]
Hi,

First of all, thank you for sharing your work with the community!

Can you provide details (maybe a paper) that can be used to cite your work in another scientific work? I am working on my master thesis and would like to attribute the credit to your work. :)

Cheers,
Rosko

**Comment by nreimers** [comment]
Hi Rosko,
happy to hear, that this code is useful. So far, there is no scientific paper etc., but you can reference in your master thesis in a footnote this github repository. This also works as a reference.

Best
Nils

**Comment by roskoN** [comment]
Thank you!
