### ISSUE TITLE
What data was used to train the included model?

### ISSUE THREAD

**Issue by mayhewsw** [nreimers/truecaser#4]
Thanks for this! We have found it useful, and would (potentially) like to cite it. When discussing it in our paper, it would be helpful to know what data the included model was trained on. Could you say what data you used?

**Comment by nreimers** [comment]
Hi,
the published pre-trained model was trained on:

From NLTK:
Brown Corpus
Reuters Corpus
Semcor Corpus
Conll2000 Corpus
State_union Corpus

Self-crawled:
TechCrunch articles (~150.000 articles)

n-gram table:
Most frequents n-grams of the Corpus of Contemporary American English (COCA) - https://www.ngrams.info/download_coca.asp

**Comment by mayhewsw** [comment]
Thanks!
