### ISSUE TITLE
Bug in trigrams loop

### ISSUE THREAD

**Issue by pashalot** [nreimers/truecaser#7]
There is probably a bug in TrainFunctions.py. 
In loop that creates trigrams missed assignment to `word` variable (`word = sentence[tokenIdx]`). So this loop uses the last value from previous loop.

**Comment by nreimers** [comment]
Can you point to the lines that you mean?

**Comment by pashalot** [comment]
https://github.com/nreimers/truecaser/blob/8bc08c4718461dda5fab7b85f72c10b4f7bcf426/TrainFunctions.py#L78

Here `word` comes from previous loop

**Comment by nreimers** [comment]
You are right. Thanks for pointing this out. Fixed it.
